-- MySQL Script generated by MySQL Workbench
-- Fri Nov 17 01:05:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema yt_enterprise_dump
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema yt_enterprise_dump
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `yt_enterprise_dump` DEFAULT CHARACTER SET utf8 ;
USE `yt_enterprise_dump` ;

-- -----------------------------------------------------
-- Table `yt_enterprise_dump`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yt_enterprise_dump`.`customer` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(255) NULL DEFAULT NULL,
  `Email` VARCHAR(255) NULL DEFAULT NULL,
  `Address` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `yt_enterprise_dump`.`shirt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yt_enterprise_dump`.`shirt` (
  `ShirtID` INT NOT NULL,
  `Size` VARCHAR(10) NULL DEFAULT NULL,
  `Color` VARCHAR(20) NULL DEFAULT NULL,
  `Deadline` DATE NULL DEFAULT NULL,
  `DesignPercentage` DECIMAL(5,2) NULL DEFAULT NULL,
  PRIMARY KEY (`ShirtID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `yt_enterprise_dump`.`buy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yt_enterprise_dump`.`buy` (
  `CustomerID` INT NOT NULL,
  `ShirtID` INT NOT NULL,
  `PurchaseDate` DATE NULL,
  INDEX `ShirtID` (`ShirtID` ASC) VISIBLE,
  CONSTRAINT `customer_shirt_purchase_ibfk_1`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `yt_enterprise_dump`.`customer` (`ID`),
  CONSTRAINT `customer_shirt_purchase_ibfk_2`
    FOREIGN KEY (`ShirtID`)
    REFERENCES `yt_enterprise_dump`.`shirt` (`ShirtID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `yt_enterprise_dump`.`quality_control_form`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yt_enterprise_dump`.`quality_control_form` (
  `QualityControlID` INT NOT NULL,
  `CheckerName` VARCHAR(45) NULL,
  `InspectionDate` DATE NULL DEFAULT NULL,
  `QualityRating` INT NULL DEFAULT NULL,
  `QualityIssues` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`QualityControlID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `yt_enterprise_dump`.`check-shirt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yt_enterprise_dump`.`check-shirt` (
  `QualityControlID` INT NOT NULL,
  `ShirtID` INT NOT NULL,
  `CustomerID` INT NOT NULL,
  PRIMARY KEY (`QualityControlID`),
  INDEX `ShirtID` (`ShirtID` ASC) VISIBLE,
  INDEX `qa_customer_id_idx` (`CustomerID` ASC) VISIBLE,
  CONSTRAINT `quality_control_shirt_ibfk_1`
    FOREIGN KEY (`QualityControlID`)
    REFERENCES `yt_enterprise_dump`.`quality_control_form` (`QualityControlID`),
  CONSTRAINT `quality_control_shirt_ibfk_2`
    FOREIGN KEY (`ShirtID`)
    REFERENCES `yt_enterprise_dump`.`shirt` (`ShirtID`),
  CONSTRAINT `qa_customer_id`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `yt_enterprise_dump`.`customer` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `yt_enterprise_dump`.`return_form`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yt_enterprise_dump`.`return_form` (
  `ReturnID` INT NOT NULL,
  `CheckerName` VARCHAR(45) NULL,
  `ReturnDate` DATE NULL DEFAULT NULL,
  `ReasonForReturn` TEXT NULL DEFAULT NULL,
  `ActionTaken` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ReturnID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `yt_enterprise_dump`.`returned`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yt_enterprise_dump`.`returned` (
  `ReturnID` INT NOT NULL,
  `ShirtID` INT NOT NULL,
  `CustomerID` INT NOT NULL,
  PRIMARY KEY (`ReturnID`),
  INDEX `ShirtID` (`ShirtID` ASC) VISIBLE,
  INDEX `returned_items_customerID_idx` (`CustomerID` ASC) VISIBLE,
  CONSTRAINT `returned_items_shirt_ibfk_1`
    FOREIGN KEY (`ReturnID`)
    REFERENCES `yt_enterprise_dump`.`return_form` (`ReturnID`),
  CONSTRAINT `returned_items_shirt_ibfk_2`
    FOREIGN KEY (`ShirtID`)
    REFERENCES `yt_enterprise_dump`.`shirt` (`ShirtID`),
  CONSTRAINT `returned_items_customerID`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `yt_enterprise_dump`.`customer` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `yt_enterprise_dump`.`add-to-wishlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yt_enterprise_dump`.`add-to-wishlist` (
  `ShirtID` INT NOT NULL,
  `CartID` INT NOT NULL,
  `CustomerID` INT NOT NULL,
  `DateAdded` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CartID`, `DateAdded`),
  INDEX `shirt_cart_ibfk_3_idx` (`CustomerID` ASC) VISIBLE,
  CONSTRAINT `shirt_cart_ibfk_1`
    FOREIGN KEY (`ShirtID`)
    REFERENCES `yt_enterprise_dump`.`shirt` (`ShirtID`),
  CONSTRAINT `shirt_cart_ibfk_3`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `yt_enterprise_dump`.`customer` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `yt_enterprise_dump`.`youtuber`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yt_enterprise_dump`.`youtuber` (
  `YouTuberID` INT NOT NULL,
  `Name` VARCHAR(50) NULL DEFAULT NULL,
  `Channel` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`YouTuberID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `yt_enterprise_dump`.`endorsement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yt_enterprise_dump`.`endorsement` (
  `YouTuberID` INT NULL,
  `ShirtID` INT NOT NULL,
  INDEX `ShirtID` (`ShirtID` ASC) VISIBLE,
  CONSTRAINT `youtuber_endorsement_ibfk_1`
    FOREIGN KEY (`YouTuberID`)
    REFERENCES `yt_enterprise_dump`.`youtuber` (`YouTuberID`),
  CONSTRAINT `youtuber_endorsement_ibfk_2`
    FOREIGN KEY (`ShirtID`)
    REFERENCES `yt_enterprise_dump`.`shirt` (`ShirtID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
